const tasks=[
  ['Build your base resume','Create one strong, ATS-friendly resume to use as your foundation.'],
  ['Add your first job','Save a role to start tracking your applications.'],
  ['Complete your profile','Help us personalize your job-search experience.'],
  ['Practice an interview','Get comfortable answering common interview questions.']
];
const initialJobs=[
  {title:'Product Designer',company:'Northstar Labs',stage:'Saved'},
  {title:'UX Researcher',company:'Brightline',stage:'Saved'},
  {title:'Senior Product Designer',company:'Orbit',stage:'Applied'},
  {title:'Design Systems Lead',company:'Canvas',stage:'Interviewing'},
  {title:'Product Designer',company:'Aperture',stage:'Offer'}
];
let jobs=JSON.parse(localStorage.getItem('compass-jobs')||'null')||initialJobs;
let completed=JSON.parse(localStorage.getItem('compass-tasks')||'[]');
const stages=['Saved','Applied','Interviewing','Offer'];
const save=()=>localStorage.setItem('compass-jobs',JSON.stringify(jobs));
function renderTasks(){const root=document.querySelector('#task-list');root.innerHTML=tasks.map((t,i)=>`<div class="task"><input class="task-check" type="checkbox" data-task="${i}" ${completed.includes(i)?'checked':''}><div class="task-content"><b>${t[0]}</b><p>${t[1]}</p></div><button data-go="${['resumes','tracker','dashboard','interview'][i]}">${completed.includes(i)?'Done':'Get started'} →</button></div>`).join('');const n=completed.length;document.querySelector('#done-count').textContent=n;document.querySelector('#percent').textContent=`${n*25}%`;document.querySelector('#progress-bar').style.width=`${n*25}%`}
function renderBoard(query=''){const board=document.querySelector('#board');board.innerHTML=stages.map(stage=>{const list=jobs.filter(j=>j.stage===stage&&(`${j.title} ${j.company}`).toLowerCase().includes(query.toLowerCase()));return `<div class="column" data-stage="${stage}"><div class="column-head">${stage}<span>${list.length}</span></div><div class="dropzone">${list.map(j=>`<article class="job-card" draggable="true" data-id="${jobs.indexOf(j)}"><div class="company-icon">${j.company.slice(0,2).toUpperCase()}</div><h3>${j.title}</h3><p>${j.company}</p><small>Added today</small></article>`).join('')}</div></div>`}).join('');setupDrag()}
function setupDrag(){let dragged;document.querySelectorAll('.job-card').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=card;card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'))});document.querySelectorAll('.column').forEach(col=>{col.addEventListener('dragover',e=>e.preventDefault());col.addEventListener('drop',e=>{e.preventDefault();if(!dragged)return;jobs[dragged.dataset.id].stage=col.dataset.stage;save();renderBoard(document.querySelector('#job-search').value)})})}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector(`#${id}`).classList.add('active-page');document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.querySelector('#page-title').textContent=document.querySelector(`[data-page="${id}"]`)?.textContent.trim()||id;document.querySelector('.sidebar').classList.remove('open')}
document.addEventListener('click',e=>{const target=e.target.closest('[data-go],[data-page]');if(target)showPage(target.dataset.go||target.dataset.page);if(e.target.matches('.task-check')){let i=+e.target.dataset.task;completed=e.target.checked?[...completed,i]:completed.filter(x=>x!==i);localStorage.setItem('compass-tasks',JSON.stringify(completed));renderTasks()} });
document.querySelector('#add-job').onclick=()=>document.querySelector('#job-dialog').showModal();
document.querySelector('#job-form').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;e.preventDefault();let data=new FormData(e.target);jobs.unshift({title:data.get('title'),company:data.get('company'),stage:data.get('stage')});save();renderBoard();e.target.reset();document.querySelector('#job-dialog').close();showPage('tracker')});
document.querySelector('#job-search').oninput=e=>renderBoard(e.target.value);
document.querySelector('#clear-jobs').onclick=()=>{if(confirm('Remove all jobs from your tracker?')){jobs=[];save();renderBoard()}};
const ignoredWords=new Set('about after also and are based been can candidates click company complete cover description design detail do experience for from have including into job jobs just key lead looking more must not our other over role skills strong team that the their they this to use we will with work working you your years');
if(window.pdfjsLib)window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
document.querySelector('#resume-file').addEventListener('change',async event=>{const file=event.target.files[0];const status=document.querySelector('#upload-status');if(!file)return;if(!window.pdfjsLib){status.textContent='PDF reader could not load. Paste the resume text instead.';return}try{status.textContent='Reading your PDF…';const data=new Uint8Array(await file.arrayBuffer());const pdf=await window.pdfjsLib.getDocument({data}).promise;const pages=[];for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber);const content=await page.getTextContent();pages.push(content.items.map(item=>item.str).join(' '))}document.querySelector('#resume-input').value=pages.join('\n\n');status.textContent=`${file.name} loaded — review extracted text below.`}catch(error){status.textContent='Could not read this PDF. Try a text-based PDF or paste the resume text.'}});
function keywordsFrom(text){const words=(text.toLowerCase().match(/[a-z][a-z+#.-]{2,}/g)||[]).filter(w=>!ignoredWords.has(w));const frequency={};words.forEach(word=>frequency[word]=(frequency[word]||0)+1);return Object.entries(frequency).sort((a,b)=>b[1]-a[1]).map(item=>item[0]).filter(word=>word.length>3).slice(0,12)}
document.querySelector('#tailor-resume').onclick=()=>{const resume=document.querySelector('#resume-input').value.trim();const jd=document.querySelector('#jd-input').value.trim();if(!resume||!jd){alert('Please upload or paste your resume and add the job description first.');return}const keywords=keywordsFrom(jd);const lower=resume.toLowerCase();const matches=keywords.filter(word=>lower.includes(word));const missing=keywords.filter(word=>!lower.includes(word));const score=Math.max(12,Math.round((matches.length/Math.max(keywords.length,1))*100));const target=jd.split(/[.\n]/)[0].slice(0,120);const summary=`Candidate with demonstrated experience in ${matches.length?matches.slice(0,6).join(', '):'the skills documented below'}, targeting ${target}.`;document.querySelector('#tailored-output').value=`PROFESSIONAL SUMMARY\n${summary}\n\nRELEVANT SKILLS\n${matches.length?matches.join(' • '):'Review the job requirements and accurately add skills you possess.'}\n\n${resume}\n\nTAILORING REVIEW\nThe following JD terms are not confirmed by the uploaded resume: ${missing.length?missing.join(', '):'None of the prominent terms.'}\nOnly add a term if you can support it with genuine experience.`;document.querySelector('#match-score').textContent=`${score}%`;document.querySelector('#match-copy').textContent=missing.length?`${matches.length} of ${keywords.length} prominent job-description terms are supported by your resume. The draft prioritizes those verified skills.`:'Your resume already supports the prominent terms from this job description.';document.querySelector('#keywords').innerHTML=keywords.map(word=>`<span>${word}${lower.includes(word)?' ✓':''}</span>`).join('');document.querySelector('#tailor-results').hidden=false;document.querySelector('#tailor-results').scrollIntoView({behavior:'smooth',block:'start'})};
function escapePdf(value){return value.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?')}
function wrapPdfLine(line,max=88){const words=line.split(/\s+/);const lines=[];let current='';words.forEach(word=>{if((current+' '+word).trim().length>max&&current){lines.push(current);current=word}else current=(current+' '+word).trim()});if(current||!lines.length)lines.push(current);return lines}
function buildPdf(text){const lines=text.replace(/\r/g,'').split('\n').flatMap(line=>line?wrapPdfLine(line):['']);const pageSize=48;const pages=[];for(let i=0;i<lines.length;i+=pageSize)pages.push(lines.slice(i,i+pageSize));const objects=['<< /Type /Catalog /Pages 2 0 R >>',''];const pageIds=[];pages.forEach((page,index)=>{const pageId=3+index*2;const contentId=pageId+1;pageIds.push(`${pageId} 0 R`);const content=['BT','/F1 11 Tf','50 770 Td','15 TL',...page.map(line=>`(${escapePdf(line)}) Tj T*`),'ET'].join('\n');objects[pageId-1]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${3+pages.length*2} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId-1]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`});objects[1]=`<< /Type /Pages /Kids [${pageIds.join(' ')}] /Count ${pages.length} >>`;objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((object,index)=>{offsets.push(pdf.length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;offsets.slice(1).forEach(offset=>pdf+=`${String(offset).padStart(10,'0')} 00000 n \n`);pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
document.querySelector('#download-resume').onclick=()=>{const blob=buildPdf(document.querySelector('#tailored-output').value);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='tailored-resume.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.querySelector('#new-contact').onclick=()=>{const name=prompt('Contact name');if(name){document.querySelector('#contact-list').insertAdjacentHTML('beforeend',`<div class="contact"><span>${name.slice(0,2).toUpperCase()}</span><b>${name}</b></div>`)}};
document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
renderTasks();renderBoard();
